/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import flowersScene from "../assets/flowers.glb"
import { useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Flowers(props) {
 
  const { scene } = useGLTF(flowersScene);

  

  return (
    // <group ref={group} {...props} dispose={null}>
    //   <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
    //     <primitive object={nodes.mixamorigHips} />
     
    //   </group>
    // </group>
    <mesh position={[2,-2,0]} scale={1.5}>
      <primitive object={scene}/>
    </mesh>
  );
}

useGLTF.preload("/kick.glb");
